import type { NextPage } from "next";
import Head from "next/head";
import { HeaderResponsive } from "src/components/Header";

const Home: NextPage = () => {
	return (
		<div className="">
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div>
				<HeaderResponsive
					links={[
						{
							link: "/about",
							label: "Features",
						},
						{
							link: "/pricing",
							label: "Pricing",
						},
						{
							link: "/learn",
							label: "Learn",
						},
						{
							link: "/community",
							label: "Community",
						},
					]}
				/>
			</div>
		</div>
	);
};

export default Home;
